spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true  #print로 남김
        format_sql: true

#logging.level:
#  org.hibernate.SQL: debug #log로 남김
# org.hibernate.type: trace #parameter보기